name: create installer

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    
    steps:

    - name: Checkout Meadow.CLI
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.CLI
        path: Meadow.CLI
        ref: develop

    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop

    - name: Checkout Meadow.Units
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: develop
        
    - name: Checkout Workbench
      uses: actions/checkout@v3
      with:
        path: Meadow.Workbench

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    
    - name: Build
      run: dotnet build -c Debug Meadow.Workbench/Source/Meadow.Workbench/Meadow.Workbench.sln

    - name: Publish
      run: dotnet publish .\Meadow.Workbench\Source\Meadow.Workbench\Meadow.Workbench.Desktop\Meadow.Workbench.Desktop.csproj -f net8.0 --no-restore -o publish

    - name: Create Velopack Release
      run: |
        dotnet tool install -g vpk
        vpk download github --repoUrl https://github.com/WildernessLabs/Meadow.Workbench
        vpk pack -u Meadow.Workbench -v 0.1.1 -p publish
        vpk upload github --repoUrlhttps://github.com/WildernessLabs/Meadow.Workbench --publish --releaseName "Meadow.Workbench 0.1.1" --tag v$0.1.1
          
