<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  
  <ItemGroup>
    <None Remove="Assets\connected.svg" />
    <None Remove="Assets\disconnected.svg" />
    <None Remove="Assets\folder.svg" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
	<PackageReference Include="Avalonia.Controls.DataGrid" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Svg.Skia" Version="11.0.0.9" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="$(AvaloniaVersion)" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Xaml.Behaviors" Version="11.0.6" />
    <PackageReference Include="DialogHost.Avalonia" Version="0.7.7" />
    <PackageReference Include="MQTTnet" Version="5.0.1.1416" />
    <PackageReference Include="MQTTnet.Server" Version="5.0.1.1416" />
    <PackageReference Include="opennetcf-orm-sqlite" Version="1.0.23048.1" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="LibGit2Sharp" Version="0.26.2" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="$(AvaloniaVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Meadow.CLI\Source\Meadow.Firmware\Meadow.Firmware.csproj" />
    <ProjectReference Include="..\..\..\..\Meadow.CLI\Source\Meadow.Hcom\Meadow.HCom.csproj" />
    <ProjectReference Include="..\..\..\..\Meadow.CLI\Source\Meadow.Linker\Meadow.Linker.csproj" />
    <ProjectReference Include="..\..\..\..\Meadow.CLI\Source\Meadow.SoftwareManager\Meadow.SoftwareManager.csproj" />
      
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>

</Project>
